sudo: required
dist: trusty
group: edge
addons:
  apt:
    packages:
      - mysql-server-5.6
      - mysql-client-core-5.6
      - mysql-client-5.6
      - postfix
  firefox: latest
  hosts:
    - magento2.travis
services:
  - rabbitmq
  - elasticsearch
language: php
php:
  - '7.3'
env:
  global:
    - COMPOSER_BIN_DIR=~/bin
    - NODE_JS_VERSION=8
    - MAGENTO_HOST_NAME="magento2.travis"
  matrix:
    - TEST_SUITE=static
matrix:
  fast_finish: true
cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.nvm
    - $HOME/node_modules
    - $HOME/yarn.lock
before_install:
  - mkdir -p ext/magento/adobe-stock-integration
  - mv !(ext) ext/magento/adobe-stock-integration/
  - ./ext/magento/adobe-stock-integration/dev/travis/before_install.sh
install:
  - cd magento2
  - composer install
  - composer config minimum-stability dev
  - composer config repositories.ext path "../ext/*/*/*"
  - composer require magento/adobe-stock-integration
before_script:
  - cp ../ext/magento/adobe-stock-integration/dev/tests/unit/phpunit.xml dev/tests/unit/phpunit.xml
  - cp -f ../ext/magento/adobe-stock-integration/dev/travis/before_script.sh dev/travis/before_script.sh
  - ./dev/travis/before_script.sh
script:
- if [ $TEST_SUITE == 'static' ]; then ! find ../ext -type f -name "*.php" -exec grep -L strict_types=1 {} + | grep ext/magento/adobe-stock-integration/; fi

after_success:
  - if [ $TEST_SUITE == 'unit' ]; then cd ../ && travis_retry coveralls; fi
