sudo: required
dist: trusty
group: edge
language: php
php:
  - '7.3'
env:
  global:
    - COMPOSER_BIN_DIR=~/bin
    - MAGENTO_HOST_NAME="magento2.travis"
  matrix:
    - TEST_SUITE=static
matrix:
  fast_finish: true
before_install:
  - mkdir -p ext/magento/adobe-stock-integration
  - mv !(ext) ext/magento/adobe-stock-integration/
script:
  - if [ $TEST_SUITE == 'static' ]; then ! find ../ext -type f -name "*.php" -exec grep -L strict_types=1 {} + | grep ext/magento/adobe-stock-integration/; fi
